# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-02-28 15:36:20
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def BDSHabitat():  # BDSHabitat

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(cellSize="30", extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", mask="CatchmentArea_sME", 
                          snapRaster="NLCD_2019.tif", workspace="C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel"):
        LakesPonds = "LakesPonds"
        CatchmentArea_sME_3_ = "CatchmentArea_sME"
        Stream_Order = "Gradient Classification"
        LakesPonds_shp = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\LakesPonds.shp"
        Gradient_Classification = "Gradient Classification"
        ME_Wetlands = "ME_Wetlands"
        CatchmentArea_sME_4_ = "CatchmentArea_sME"
        Developed_areas_in_catchments = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\CatchmentArea_devel"
        Forested_areas_in_catchments = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\CatchmentArea_forest"
        CatchmentArea_sME = "CatchmentArea_sME"

        # Process: Pairwise Buffer (Pairwise Buffer) (analysis)
        LakesPonds_PairwiseBuffer = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\LakesPonds_PairwiseBuffer"
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            arcpy.analysis.PairwiseBuffer(in_features=LakesPonds, out_feature_class=LakesPonds_PairwiseBuffer, buffer_distance_or_field="-60 Meters")

        # Process: Erase (3) (Erase) (analysis)
        LakesPonds_Shoreline60 = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\LakesPonds_Shoreline60"
        arcpy.analysis.Erase(in_features=LakesPonds, erase_features=LakesPonds_PairwiseBuffer, out_feature_class=LakesPonds_Shoreline60)

        # Process: Clip (Clip) (analysis)
        Lakes_and_ponds_in_southern_ME = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\LakesPonds_sME"
        arcpy.analysis.Clip(in_features=LakesPonds_Shoreline60, clip_features=CatchmentArea_sME_3_, out_feature_class=Lakes_and_ponds_in_southern_ME)

        # Process: Dissolve (Dissolve) (management)
        Lakes_and_ponds_dissolve = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\LakesPonds_sME_Dissolve"
        arcpy.management.Dissolve(in_features=Lakes_and_ponds_in_southern_ME, out_feature_class=Lakes_and_ponds_dissolve)

        # Process: Polygon to Raster (3) (Polygon to Raster) (conversion)
        Lakes_and_ponds_raster = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\LakesPonds_sME_raster"
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            arcpy.conversion.PolygonToRaster(in_features=Lakes_and_ponds_dissolve, value_field="OBJECTID", out_rasterdataset=Lakes_and_ponds_raster)

        # Process: Reclassify (5) (Reclassify) (sa)
        Lake_Pond_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\LakePond_rcls"
        Reclassify_5_ = Lake_Pond_reclass
        Lake_Pond_reclass = arcpy.sa.Reclassify(Lakes_and_ponds_raster, "VALUE", "1 5;NODATA 0", "DATA")
        Lake_Pond_reclass.save(Reclassify_5_)


        # Process: Erase (Erase) (analysis)
        StreamOrder_LakeErase = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\StreamOrder_LakeErase"
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            arcpy.analysis.Erase(in_features=Stream_Order, erase_features=LakesPonds_shp, out_feature_class=StreamOrder_LakeErase)

        # Process: Select (5) (Select) (analysis)
        Best_Stream_Order_Select = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestStreamOrderSelect"
        arcpy.analysis.Select(in_features=StreamOrder_LakeErase, out_feature_class=Best_Stream_Order_Select, where_clause="D_SZCL4 = 'Headwater/Creek' Or D_SZCL4 = 'Small River'")

        # Process: Distance Accumulation (Distance Accumulation) (sa)
        Best_Stream_Order_Distance_Accumulation = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestStreamOrd_DistAcc"
        Distance_Accumulation = Best_Stream_Order_Distance_Accumulation
        Out_back_direction_raster_5_ = ""
        Out_source_direction_raster = ""
        Out_source_location_raster = ""
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Best_Stream_Order_Distance_Accumulation = arcpy.sa.DistanceAccumulation(Best_Stream_Order_Select, "", "", "", "", "BINARY 1 -30 30", "", "BINARY 1 45", Out_back_direction_raster_5_, Out_source_direction_raster, Out_source_location_raster, "", "", "", "", "PLANAR")
            Best_Stream_Order_Distance_Accumulation.save(Distance_Accumulation)


        # Process: Reclassify (6) (Reclassify) (sa)
        Best_Stream_Order_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestStreamOrd_rcls"
        Reclassify_6_ = Best_Stream_Order_reclass
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Best_Stream_Order_reclass = arcpy.sa.Reclassify(Best_Stream_Order_Distance_Accumulation, "VALUE", "0 30 2;30 100000 0;NODATA 0", "DATA")
            Best_Stream_Order_reclass.save(Reclassify_6_)


        # Process: Select (6) (Select) (analysis)
        Good_Stream_Order_Select = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodStreamOrderSelect"
        arcpy.analysis.Select(in_features=StreamOrder_LakeErase, out_feature_class=Good_Stream_Order_Select, where_clause="D_SZCL4 = 'Medium River'")

        # Process: Distance Accumulation (2) (Distance Accumulation) (sa)
        Best_Stream_Order_Distance_Accumulation_2_ = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodStreamOrd_DistAcc"
        Distance_Accumulation_2_ = Best_Stream_Order_Distance_Accumulation_2_
        Out_back_direction_raster_3_ = ""
        Out_source_direction_raster_2_ = ""
        Out_source_location_raster_2_ = ""
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Best_Stream_Order_Distance_Accumulation_2_ = arcpy.sa.DistanceAccumulation(Good_Stream_Order_Select, "", "", "", "", "BINARY 1 -30 30", "", "BINARY 1 45", Out_back_direction_raster_3_, Out_source_direction_raster_2_, Out_source_location_raster_2_, "", "", "", "", "PLANAR")
            Best_Stream_Order_Distance_Accumulation_2_.save(Distance_Accumulation_2_)


        # Process: Reclassify (7) (Reclassify) (sa)
        Good_Stream_order_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodStreamOrd_rcls"
        Reclassify_7_ = Good_Stream_order_reclass
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Good_Stream_order_reclass = arcpy.sa.Reclassify(Best_Stream_Order_Distance_Accumulation_2_, "VALUE", "0 30 1;30 200000 0;NODATA 0", "DATA")
            Good_Stream_order_reclass.save(Reclassify_7_)


        # Process: Con (3) (Con) (ia)
        Stream_order_con = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\StreamOrder_con"
        Con_3_ = Stream_order_con
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Stream_order_con = arcpy.ia.Con(Best_Stream_Order_reclass, Best_Stream_Order_reclass, Good_Stream_order_reclass, "Value > 0")
            Stream_order_con.save(Con_3_)


        # Process: Erase (2) (Erase) (analysis)
        StreamGradient_LakeErase = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\StreamGradient_LakeErase"
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            arcpy.analysis.Erase(in_features=Gradient_Classification, erase_features=LakesPonds_shp, out_feature_class=StreamGradient_LakeErase)

        # Process: Select (Select) (analysis)
        Best_Stream_Gradient_Select = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestGradientSelect"
        arcpy.analysis.Select(in_features=StreamGradient_LakeErase, out_feature_class=Best_Stream_Gradient_Select, where_clause="D_NESLPCL LIKE '%Very Low Gradient: <0.02\\%%' ESCAPE '\\' Or D_NESLPCL LIKE '%Low Gradient: >= 0.02 < 0.1\\%%' ESCAPE '\\'")

        # Process: Distance Accumulation (3) (Distance Accumulation) (sa)
        Best_Stream_Order_Distance_Accumulation_3_ = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestStreamGrad_DistAcc"
        Distance_Accumulation_3_ = Best_Stream_Order_Distance_Accumulation_3_
        Out_back_direction_raster_4_ = ""
        Out_source_direction_raster_3_ = ""
        Out_source_location_raster_3_ = ""
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Best_Stream_Order_Distance_Accumulation_3_ = arcpy.sa.DistanceAccumulation(Best_Stream_Gradient_Select, "", "", "", "", "BINARY 1 -30 30", "", "BINARY 1 45", Out_back_direction_raster_4_, Out_source_direction_raster_3_, Out_source_location_raster_3_, "", "", "", "", "PLANAR")
            Best_Stream_Order_Distance_Accumulation_3_.save(Distance_Accumulation_3_)


        # Process: Reclassify (3) (Reclassify) (sa)
        Best_stream_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestStream_rcls"
        Reclassify_3_ = Best_stream_reclass
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", mask="CatchmentArea_sME"):
            Best_stream_reclass = arcpy.sa.Reclassify(Best_Stream_Order_Distance_Accumulation_3_, "VALUE", "0 30 3;30 150000 0;NODATA 0", "DATA")
            Best_stream_reclass.save(Reclassify_3_)


        # Process: Select (2) (Select) (analysis)
        Good_Stream_Gradient_Select = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodGradientSelect"
        arcpy.analysis.Select(in_features=StreamGradient_LakeErase, out_feature_class=Good_Stream_Gradient_Select, where_clause="D_NESLPCL LIKE '%Low-Moderate Gradient: >= 0.1 < 0.5\\%%' ESCAPE '\\'")

        # Process: Distance Accumulation (4) (Distance Accumulation) (sa)
        Best_Stream_Order_Distance_Accumulation_4_ = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodStreamGrad_DistAcc"
        Distance_Accumulation_4_ = Best_Stream_Order_Distance_Accumulation_4_
        Out_back_direction_raster_6_ = ""
        Out_source_direction_raster_4_ = ""
        Out_source_location_raster_4_ = ""
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Best_Stream_Order_Distance_Accumulation_4_ = arcpy.sa.DistanceAccumulation(Good_Stream_Gradient_Select, "", "", "", "", "BINARY 1 -30 30", "", "BINARY 1 45", Out_back_direction_raster_6_, Out_source_direction_raster_4_, Out_source_location_raster_4_, "", "", "", "", "PLANAR")
            Best_Stream_Order_Distance_Accumulation_4_.save(Distance_Accumulation_4_)


        # Process: Reclassify (4) (Reclassify) (sa)
        Good_stream_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodStream_rcls"
        Reclassify_4_ = Good_stream_reclass
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Good_stream_reclass = arcpy.sa.Reclassify(Best_Stream_Order_Distance_Accumulation_4_, "VALUE", "0 30 2;30 160000 0;NODATA 0", "DATA")
            Good_stream_reclass.save(Reclassify_4_)


        # Process: Con (Con) (sa)
        Stream_gradient_con = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\StreamGrad_con"
        Con = Stream_gradient_con
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Stream_gradient_con = arcpy.sa.Con(Best_stream_reclass, Best_stream_reclass, Good_stream_reclass, "Value > 0")
            Stream_gradient_con.save(Con)


        # Process: Plus (2) (Plus) (sa)
        Stream_order_and_gradient = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\StreamOrdGrad_plus"
        Plus_2_ = Stream_order_and_gradient
        Stream_order_and_gradient = arcpy.sa.Plus(Stream_order_con, Stream_gradient_con)
        Stream_order_and_gradient.save(Plus_2_)


        # Process: Con (2) (Con) (sa)
        Lake_Pond_Stream_con = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\LakeStream_con"
        Con_2_ = Lake_Pond_Stream_con
        Lake_Pond_Stream_con = arcpy.sa.Con(Lake_Pond_reclass, Lake_Pond_reclass, Stream_order_and_gradient, "Value > 0")
        Lake_Pond_Stream_con.save(Con_2_)


        # Process: Clip (2) (Clip) (analysis)
        Wetlands_sME = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\Wetlands_sME"
        arcpy.analysis.Clip(in_features=ME_Wetlands, clip_features=CatchmentArea_sME_4_, out_feature_class=Wetlands_sME)

        # Process: Select (3) (Select) (analysis)
        Best_Wetland_Select_aquatic_bed_ = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestWetlSelect"
        arcpy.analysis.Select(in_features=Wetlands_sME, out_feature_class=Best_Wetland_Select_aquatic_bed_, where_clause="ATTRIBUTE LIKE '%AB%' And (WETLAND_TY <> 'Estuarine and Marine Deepwater' And WETLAND_TY <> 'Estuarine and Marine Wetland')")

        # Process: Polygon to Raster (4) (Polygon to Raster) (conversion)
        Best_Wetland_raster = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestWetl_raster"
        arcpy.conversion.PolygonToRaster(in_features=Best_Wetland_Select_aquatic_bed_, value_field="OBJECTID", out_rasterdataset=Best_Wetland_raster)

        # Process: Reclassify (8) (Reclassify) (sa)
        Best_Wetland_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\BestWetl_rcls"
        Reclassify_8_ = Best_Wetland_reclass
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            Best_Wetland_reclass = arcpy.sa.Reclassify(Best_Wetland_raster, "VALUE", "1 580 4;NODATA 0", "DATA")
            Best_Wetland_reclass.save(Reclassify_8_)


        # Process: Select (4) (Select) (analysis)
        Good_Wetland_Select = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodWetlandSelect"
        arcpy.analysis.Select(in_features=Wetlands_sME, out_feature_class=Good_Wetland_Select, where_clause="(ATTRIBUTE LIKE 'R%EM%' Or ATTRIBUTE LIKE 'L%EM%' Or ATTRIBUTE LIKE 'L2UB2%' Or ATTRIBUTE LIKE 'L2UB3%' Or ATTRIBUTE LIKE 'L2UB4%' Or ATTRIBUTE LIKE 'L2US2%' Or ATTRIBUTE LIKE 'L2US3%' Or ATTRIBUTE LIKE 'L2US4%') And (WETLAND_TY <> 'Estuarine and Marine Deepwater' And WETLAND_TY <> 'Estuarine and Marine Wetland')")

        # Process: Polygon to Raster (5) (Polygon to Raster) (conversion)
        Good_Wetland_raster = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodWetland_raster"
        arcpy.conversion.PolygonToRaster(in_features=Good_Wetland_Select, value_field="OBJECTID", out_rasterdataset=Good_Wetland_raster)

        # Process: Reclassify (9) (Reclassify) (sa)
        Good_Wetland_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\GoodWetl_rcls"
        Reclassify_9_ = Good_Wetland_reclass
        with arcpy.EnvManager(snapRaster="NLCD_2019.tif"):
            Good_Wetland_reclass = arcpy.sa.Reclassify(Good_Wetland_raster, "VALUE", "1 108723 3;NODATA 0", "DATA")
            Good_Wetland_reclass.save(Reclassify_9_)


        # Process: Con (4) (Con) (sa)
        Wetland_con = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\Wetland_con"
        Con_4_ = Wetland_con
        Wetland_con = arcpy.sa.Con(Best_Wetland_reclass, Best_Wetland_reclass, Good_Wetland_reclass, "Value > 0")
        Wetland_con.save(Con_4_)


        # Process: Plus (3) (Plus) (ia)
        Lakes_Ponds_Streams_Wetlands = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\LakeWetland_plus"
        Plus_3_ = Lakes_Ponds_Streams_Wetlands
        Lakes_Ponds_Streams_Wetlands = arcpy.ia.Plus(Lake_Pond_Stream_con, Wetland_con)
        Lakes_Ponds_Streams_Wetlands.save(Plus_3_)


        # Process: Select (7) (Select) (analysis)
        Saltwater_habitats = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\Wetlands_sME_Select"
        arcpy.analysis.Select(in_features=Wetlands_sME, out_feature_class=Saltwater_habitats, where_clause="WETLAND_TY = 'Estuarine and Marine Deepwater' Or WETLAND_TY = 'Estuarine and Marine Wetland'")

        # Process: Polygon to Raster (6) (Polygon to Raster) (conversion)
        Saltwater_Wetland_raster = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\SaltWetlands_Raster"
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            arcpy.conversion.PolygonToRaster(in_features=Saltwater_habitats, value_field="OBJECTID", out_rasterdataset=Saltwater_Wetland_raster)

        # Process: Reclassify (12) (Reclassify) (sa)
        Saltwater_rcls = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\Saltwater_rcls"
        Reclassify_12_ = Saltwater_rcls
        Saltwater_rcls = arcpy.sa.Reclassify(Saltwater_Wetland_raster, "VALUE", "1 14500 NODATA;NODATA 0", "DATA")
        Saltwater_rcls.save(Reclassify_12_)


        # Process: Plus (6) (Plus) (sa)
        Freshwater_Habitats = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\FreshwaterHabitat"
        Plus_6_ = Freshwater_Habitats
        Freshwater_Habitats = arcpy.sa.Plus(Lakes_Ponds_Streams_Wetlands, Saltwater_rcls)
        Freshwater_Habitats.save(Plus_6_)


        # Process: Reclassify (11) (Reclassify) (sa)
        Land_values_changed_to_NODATA = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\TerrestrialHabitat_rcls"
        Reclassify_11_ = Land_values_changed_to_NODATA
        Land_values_changed_to_NODATA = arcpy.sa.Reclassify(Freshwater_Habitats, "VALUE", "0 NODATA;1 1;2 2;3 3;4 4;5 5;6 6;7 7;8 8;9 9", "DATA")
        Land_values_changed_to_NODATA.save(Reclassify_11_)


        # Process: Polygon to Raster (Polygon to Raster) (conversion)
        Catchments_with_developed_area_raster_ = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\CatchmentArea_devel_Raster"
        arcpy.conversion.PolygonToRaster(in_features=Developed_areas_in_catchments, value_field="Prop_devel", out_rasterdataset=Catchments_with_developed_area_raster_)

        # Process: Reclassify (10) (Reclassify) (sa)
        Developed_areas_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\Devel_rcls"
        Reclassify_10_ = Developed_areas_reclass
        Developed_areas_reclass = arcpy.sa.Reclassify(Catchments_with_developed_area_raster_, "VALUE", "0 0.060000 4;0.060000 0.130000 3;0.130000 0.270000 2;0.270000 1 1;NODATA 0", "DATA")
        Developed_areas_reclass.save(Reclassify_10_)


        # Process: Polygon to Raster (2) (Polygon to Raster) (conversion)
        Catchments_with_forested_area_raster_ = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\CatchmentArea_forest_Raster"
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            arcpy.conversion.PolygonToRaster(in_features=Forested_areas_in_catchments, value_field="Prop_forest", out_rasterdataset=Catchments_with_forested_area_raster_)

        # Process: Reclassify (2) (Reclassify) (sa)
        Forested_areas_reclass = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\Forest_rcls"
        Reclassify_2_ = Forested_areas_reclass
        Forested_areas_reclass = arcpy.sa.Reclassify(Catchments_with_forested_area_raster_, "VALUE", "0 0.280000 1;0.280000 0.600000 2;0.600000 0.750000 3;0.750000 1 4;NODATA 0", "DATA")
        Forested_areas_reclass.save(Reclassify_2_)


        # Process: Plus (Plus) (sa)
        Land_cover_reclass_values = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb\\Land_cover_value"
        Plus = Land_cover_reclass_values
        Land_cover_reclass_values = arcpy.sa.Plus(Developed_areas_reclass, Forested_areas_reclass)
        Land_cover_reclass_values.save(Plus)


        # Process: Plus (4) (Plus) (sa)
        BDSPredictedHabitat2_tif = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\BDSPredictedHabitat2.tif"
        Plus_4_ = BDSPredictedHabitat2_tif
        with arcpy.EnvManager(extent="315460.595164495 4764984.51202216 646206.25439123 5031048.3915301 PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
            BDSPredictedHabitat2_tif = arcpy.sa.Plus(Land_values_changed_to_NODATA, Land_cover_reclass_values)
            BDSPredictedHabitat2_tif.save(Plus_4_)


        # Process: Raster to Polygon (2) (Raster to Polygon) (conversion)
        Predicted_Bridle_Shiner_Habitat_Polygon_ = "C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\PredictedHabitatPolygon.shp"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", outputMFlag="Disabled", outputZFlag="Disabled"):
            arcpy.conversion.RasterToPolygon(in_raster=BDSPredictedHabitat2_tif, out_polygon_features=Predicted_Bridle_Shiner_Habitat_Polygon_, simplify="NO_SIMPLIFY")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", scratchWorkspace="C:\\Users\\Lara\\OneDrive - University of Maine System\\LSK_MS_Files\\Bridle Shiner Research\\Proposal\\HabitatSuitability\\HabitatModel\\Final_Project_Katz.gdb"):
        BDSHabitat()
